version: 2
jobs:
  build:
    working_directory: /jonbretman
    docker:
      - image: node:8.9.4
    steps:
      - checkout
      - run:
          name: Install
          command: |
            yarn install --frozen-lockfile
      - run:
          name: Build
          command: |
            yarn build
      - run:
          name: Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then \
              apt-get update
              apt-get install -y python-dev
              wget https://bootstrap.pypa.io/get-pip.py
              python get-pip.py
              pip install --upgrade awscli
              apt-get clean
              rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
              aws s3 sync public s3://www.jonbretman.co.uk
            fi